# ---------- Aplicacion ----------
spring.application.name=FinCore
server.port=8080
server.servlet.context-path=/

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/fincore_db?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Jose76572260@}

# ---------- JPA / Hibernate ----------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ---------- Thymeleaf ----------
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ---------- Multipart ----------
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ---------- Logging ----------
logging.level.root=INFO
logging.level.pe.edu.utp.fincore=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.file.name=logs/fincore.log